[package]
name = "bevy_prefab_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_editor_pls = "*"
bevy = "0.10.1"
ron = "*"
egui = "*"